name: Deploy Flask API to Azure

on:
  push:
    branches:
      - main  # Déclenchement automatique à chaque push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Récupérer le code source

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installation des dépendances

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-flask-api"  # Nom de ton application Azure
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Utilisation du secret GitHub
